version: '3.1'
services:

  api:
    build:
      context: .
      dockerfile: ./sbin/docker/dev-alpine.dockerfile
    command: run ./bin/launcher/main.go
    volumes:
      - esdata1:/go-mock
    environment:
      - ENV=dev
    ports:
      - 8001:8001
      - 8002:8002
      
  redis:
    image: redis:3.0-alpine
    ports:
      - 6379:6379

  postgres:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      ports:
        #- 7001:5432
        - 7001:7001

  mysql:
      image: mysql
      restart: always
      environment:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: password
      ports:
          #- 7002:3306
          - 7002:7002

  manager:
      image: adminer
      restart: always
      ports:
        - 9999:9999

volumes:
  esdata1:
    driver: local
